### ISSUE TITLE
Show "NO TRADES" instead of LastPrice of 0 for tokens that have zero buyers.

### ISSUE THREAD

**Issue by dcts** [dcts/radix.meme#160]
What is the first price for a memecoin when no token has yet been purchased? e.g. purchasing the first token off the bonding curve?

I need a price that I can show on the UI, currently it shows undefined which will be turned into a 0.

Once we have this number, I will:
- create a const variable that holds this value and will export so it can be imported anywhere in the code
- update the cards on the landing page
- update the token details page

**Comment by fliebenberg** [comment]
The price would be 0 if no tokens has been created. So it is correct to show a price of 0.

**Comment by dcts** [comment]
Ok makes sense! I'll ask @maurojose what to do on the UI, maybe we can show "no trades yet" or something else to make it clearer to the user.

**Comment by dcts** [comment]
Update: we should show "no trades" in greyed out font if the token has not traded yet instead of showing a LastPrice of 0. Will implement this.

**Comment by fliebenberg** [comment]
This is probably a technicality, but just be aware that the token can have 0 last price even after there has been some trades. It will have 0 price whenever all the tokens have been sold. We could show "No tokens issued yet" as well.
But happy for you to decide.

**Comment by dcts** [comment]
Hm technically even "No tokens issued yet" would be false, as the tokens have been issued and burned back to the token curve. I kinda prefer keeping it simple and leave with "no trades" but it is not 100% accurate I agree. 

What do you think @maurojose ?

**Comment by dcts** [comment]
Talked to Mauro and we came up with the following solution:
- instead of showing the "LastPrice", we will show "Price" (and use LastPrice as reference)
- if no tokens were bought, we will show the lowest price possible (how much does it cost to buy the first token? This should be deterministic and easy to compute, right? @fliebenberg

**Comment by fliebenberg** [comment]
Technically the lowest price is 0.000000000000000001 (the price is accurate to 18 decimals). So the price is determined by how much you buy the first time. If you bought 0.1 XRD worth of tokens, the price will be 0.00000000000001. If you bought 1 XRD worth of tokens the price will be 0.00000000000100 (100X bigger).
I also like calling it price rather than last price.
"No tokens issued" is correct, as there will be 0 supply of the tokens at this point. The user will see 0 supply for the token if they look it up on the Radix explorer or any other tool.
